### ISSUE TITLE
[Question] Leaf routes redirection

### ISSUE THREAD

**Issue by lljr** [rockandrollwithemberjs/rarwe-issues#463]
The book says:

> The Ember router can only transition to leaf routes. bands.band has three child routes,
bands.band.songs, bands.band.details and the implicit bands.band.index. When we instruct
Ember to go to a route which has subroutes (like bands.band), the actual transition will be made to its
index route (bands.band.index).

When transitioning from `/bands/led-zeppelin/songs` to `/bands/pearl-jam` (by clicking the link) the router lands on `/bands/pearl-jam/details`. The route movement would be from `bands.band.songs` to (by clicking the link) `bands.band` to land on `bands.band.songs` again. If by being in `/bands/led-zeppelin/songs`, isn't this `bands.band.songs` which is a subroute of `bands.band`. Then, the redirection shouldn't it be to `bands.band.index` instead of `bands/pearl-jam/details` (`bands.band.details`)

I'm a bit confused.

**Comment by balinterdi** [comment]
Right, I think that part is hard to get, and I should clarify that part since it can be quite confusing.

The main thing to understand is that from a routing perspective we have to distinguish two scenarios:

1) **The app is loaded up on a URL.** In this case, the router traverses the route tree from the very top (application route) all the way to the destination leaf route. We might call this "initial route rendering".
2) **A route transition is made from within the app**, via `<LinkTo>`, `transitionTo`, or `replaceWith`. In this case, no tree traversal is carried out, only the hooks of the source and destination routes are triggered. We might call this "route update".

(With "initial route rendering" and "route update", I'm trying to make an analogy to the two ways that components are rendered – initial render and update. Not sure if that's useful.)

This second point helps explain why a `redirect` hook defined in `bands.band` doesn't trigger when a user goes from `bands.band.details` to `bands.band.index`.

You can see the following if you flip the `ENV.APP.LOG_TRANSITIONS` and `ENV.APP.LOG_TRANSITIONS_INTERNAL` to true in `config/environment.js`. I should totally mention this in the book. If you do, you'll see the following detailed information about route transitions:

![Screenshot 2020-07-10 at 17 34 08](https://user-images.githubusercontent.com/5022/87172480-995bb180-c2d4-11ea-9518-d8980e3f5926.png)

I should probably also create a graph to improve the strength of the explanation.

Does the above make sense?

**Comment by lljr** [comment]
I'll use [Ember's routing section](https://guides.emberjs.com/release/routing/) as a reference for the following paragraphs in this comment.

> The URL can be set in a few ways:
>     1. The user loads the app for the first time.
>     2. The user changes the URL manually, such as by clicking the back button or by editing the address bar.
>     3. The user clicks a link within the app.
>     4. Some other event in the app causes the URL to change.

I edited the list to a number list to facilitate the referencing to each point.

In chapter 10 the URLs get remapped: `bands` to `/`, `bands.band` to `/bands/:id` and `bands.new` to `bands/new`. Booting the app for the first time, via `1`,  means hitting `bands`. However, there exists an implicit `index` sub-route, which means it's really transitioning to `bands.index` (is this correct?). Assuming the previous statement is true, the hooks for `bands` and `bands.index` run. Note that only `bands` defines hooks that fetch it's bands data. The active route ends in `bands.index`.

Now, going back to your comment
> *A route transition is made from within the app*... In this case, no tree traversal is carried out, only the hooks of the source and destination routes are triggered.

That means that *after* booting the app, as described in the paragraph above, we're traveling via `2` from `bands.index`, to `bands.band`, to redirect from `bands.band` to either `bands.band.details` or `bands.band.songs` with the `redirect` hook in `bands.band`. We later fix the redirect by placing the logic on `bands.band.index`, which brings me the to details of Ember routing.  

Given that Ember can only transition to leaf routes, when doing so, via `2`, what we're actually doing the first time is transitioning from `bands.index` to `bands.band`, which is why the `redirect` hook runs and lands us in either `bands.band.details` or `bands.band.songs`.  

Let's say - following from the previous paragraph - we finally land in `bands.band.details`.  As mentioned in the original comment in this post, this transition succeeds. Is it because we're originally traveling from two sibling routes `bands.index` to `bands.band`? Without the fix, this would not work if we re-click on the band (via `2`) because *Ember can only transition to leaf routes*. That's exactly why we move the redirect logic to `bands/bands/index.js`'s `redirect` hook. 

This brings me back to what I said earlier about each parent's routes implicit `index` sub-route. It means that originally, jumping from `bands.index` to `bands.band` will finalize in `bands.band.index`, just as booting the app initially hits `bands` but ends in `bands.index`. I'll try and be more specific here because I think this is the important part. After clicking on a band, all hooks run for `bands.band`. When the `redirect` hook is ran, does it mean that it initially has logic to redirect to `bands.band.index`? Is this same thing happening when first loading `bands`. Does `bands` end in `bands.index` because after the hook for `redirect` runs, it says to finish in `bands.index`?

If so 
> When we instruct
Ember to go to a route which has subroutes (like bands.band), the actual transition will be made to its
index route (bands.band.index).

It'd be good to mention the hooks that run in `bands.band`. I'm guessing there's a `redirect` hook that initially has logic to transition to `bands.band.index`.  Now this was just the scenario in which a user *first* clicks on a band. Something similar happens afterwards.

Let's say now I'm on a band's songs list. The active route would be `bands.band.songs` for that specific band. This is a leaf route. However, when I click on the bands list to see another band, the redirect (*without* the fix i.e. on `bands/band.js`'s `redirect` hook) I can successfully transition to that bands leaf route. This is where I'm confused. Without the fix, we're trying to move from `bands.band.songs` to `bands.band`. Doesn't that violate *Ember can only transition to leaf routes*? Why is the transition successful? Is it because we're transitioning from two different Route instances?

**Comment by lljr** [comment]
In page 198 it says: "If we load up the application on /bands/pearl-jam, everything works as expected and the app is
transitioned to the bands.band.details route" do you mean by editing the address bar? 

I think the easiest way to clear up the issue is by loading up /bands/pearl-jam in the browser. Wait for the transition to `/bands/pearl-jam/details` then finally click on the link to Led Zeppelin. You'll be redirected to `bands/led-zeppelin/songs`, which means the transition hit the redirect hook in `bands/band.js`. I'm assuming this is so because if I go back to Pearl Jam's page by clicking its link, I will land in `bands/pear-jam/details`. If I click *again* I will be redirected to `bands/pearl-jam`. This behavior is explained in the book. However, why is the redirect working when I transition from Pearl Jam to Led Zeppelin? I should be expecting the URL to e `bands/led-zeppelin` but instead it's `bands/led-zeppelin/songs`

**Comment by balinterdi** [comment]
Hey Jonathan,

Sorry, I was somewhat sloppy in my explanations (and possibly wrong somewhere).

I think it's easier to understand routing in Ember by keeping these two rules in mind:

1. **Transitions can only happen to leaf routes.** If a route has nested child routes (like `bands.band`, a transition initiated to `bands.band` is actually a transition to its implicit index route, `bands.band.index`.
2. **Ember's router does as little to arrive at the destination route as possible**.

Let's see the cases in the app we discuss above.

### App boot

If the app is being loaded, there's no source route yet, so Ember needs to traverse all routes in the routing tree to arrive at the destination route.
![route-transition-scenarios-app-boot](https://user-images.githubusercontent.com/5022/88382258-61f70580-cda8-11ea-97a0-6719600293f7.png)

### Going from the band page of one band to another band's

For example, we're on the Details page of Pearl Jam, and we click the Led Zeppelin link in the band list (in the sidebar). In terms of routes, that'd mean going from `bands.band.details` to `bands.band.index` *of another band*.

Ember realizes that it needs to go through the `bands.band` route because the dynamic segment in the URL. (I'm not 100% sure about this, but I think it should be that.). So it triggers the `model` hook of `bands.band`, to possibly load the data for the dynamic segment, and then the `redirect` hook in there. That's why this scenario works.

![route-transition-scenarios-to-another-band-link](https://user-images.githubusercontent.com/5022/88382362-98348500-cda8-11ea-8078-7e1ec0c7a356.png)

### Going from the band page of a band to the same band page

For example, we're on the Details page of Pearl Jam, and we click the Pearl Jam link in the band list (in the sidebar). In terms of routes, that'd mean going from `bands.band.details` to `bands.band.index` *of the same band*.

Ember realizes it doesn't need to pass through the `bands.band` route as it is already there – the band, the dynamic segment doesn't change.

![route-transition-scenarios-to-same-band-link-before-fix](https://user-images.githubusercontent.com/5022/88382859-a505a880-cda9-11ea-91e1-a83da2b51719.png)

Our logic in the `redirect` hook of the `bands.band` route doesn't trigger.

However, the destination route is still `bands.band.index` so if we place the redirection logic there, it gets triggered as it should:

![route-transition-scenarios-to-same-band-link-after-fix](https://user-images.githubusercontent.com/5022/88383092-1cd3d300-cdaa-11ea-88d8-93aec0beba4d.png)

**Comment by lljr** [comment]
> Ember realizes that it needs to go through the bands.band route because the dynamic segment in the URL. (I'm not 100% sure about this, but I think it should be that.).

It would be good to confirm this because it would clear up the confusion.  I'd like to know, too, how this works under the hood because it'd be easier to understand in the long run.

Thank you for your explanation, Balint, it was helpful.

**Comment by balinterdi** [comment]
> It would be good to confirm this because it would clear up the confusion. I'd like to know, too, how this works under the hood because it'd be easier to understand in the long run.

I verified this by adding a `<LinkTo @route="bands.band.songs" @model="pearl-jam">Pearl Jam songs</LinkTo>` to the band navigation template which has a Details and Songs tab of the band we're displaying.

Starting from the band's (let's say, Red Hot Chili Peppers) details page (`/bands/red-hot-chili-peppers/details`), I first clicked the "Songs" link:

![Image 2020-07-31 at 4 45 18 PM](https://user-images.githubusercontent.com/5022/89046899-ebc94480-d34d-11ea-9083-92aeacc79da8.png)

I then reloaded the app on the `/bands/red-hot-chili-peppers/details` URL and clicked the "Songs of Pearl Jam" link:

![Image 2020-07-31 at 4 47 39 PM](https://user-images.githubusercontent.com/5022/89046898-ea981780-d34d-11ea-93b2-76fc5dad282d.png)

We can see that in the latter case, it also goes through the `bands.band` route.

I think the unifying principle along which this can best be understood this is *that Ember will map the URL segments to routes, and activate the hooks of those routes –and those routes only– that it hasn't resolved yet.*

Let's see how this applies to the previous examples:

1. Before the initial load nothing has been resolved, so if the app if booted up on `/bands/pearl-jam/songs`, it activates the routes that are mapped to each URL segment (`application`, `bands`, `bands.band`, `bands.band.songs`)
2. When we're on `/bands/pearl-jam/songs` and the URL generated by the route we're transitioning to is `/bands/pearl-jam/details`, the only segment Ember's router needs to resolve is the last one, `details`, so only that route is activated.
3. When we're on `/bands/pearl-jam/songs` and we go to `/bands/led-zeppelin/`, then Ember first activates the `bands.band` route and then the `bands.bands.index` routes (as we can only transition to leaf routes).
4. When we're on `/bands/pearl-jam/songs` and we go to `/bands/pearl-jam/`, then Ember only activates the `bands.band.index` route. It doesn't need to activate the `bands.band` route as the corresponding URL segment, `pearl-jam` has already been resolved.

**Comment by balinterdi** [comment]
As a side note, you can create a route yourself, that serves as the root for that level, like so:

```js
Router.map(function() {
  this.route('bands', { path: '/' }, function() {
    this.route('band', { path: '/bands/:id' }, function() {
      this.route('songs');
      this.route('details');
      this.route('root', { path: '/' });
    });
    this.route('new', { path: 'bands/new' });
  });
});
```

In that case, it supersedes the `index` route. The `index` route is not even generated for that level, as you explicitly created your own.

So if you go from `/bands/pearl-jam/songs` to `/bands/led-zeppelin/`, then order of route activation is `bands.band`, and then `bands.band.root`.

**Comment by lljr** [comment]
Just to make sure I understood, allow me to reiterate. 

Ember will map URL segments to Routes. When someone enters a URL into an address bar in a browser, Ember will match each URL segment to a Route. A Route has hooks that trigger the _first_ time that Route loads. When a URL gets typed, for the first time, a Route that matches the URL will load.

In the case of nested Routes. Ember will match each segment to each child Route. 
1. If it's the first time the nested Route loads, Ember will trigger the hooks for all the ancestors.
2. If it's NOT the first time the nested Route loads, Ember will not trigger those hooks.

## Traversing Routes
In the case a Child Route travels to its siblings, the Route loads (would it be correct to say instantiates?) for the URL segment that changed.
