### ISSUE TITLE
Consider further elaborating on partially applied functions in Components

### ISSUE THREAD

**Issue by balinterdi** [rockandrollwithemberjs/rarwe-issues#464]
I think this part is one of the most difficult ones to understand so it might makes sense to go into further details.

Here's what I wrote to a reader (via email):

> The trick is that `fn` creates what is known (in math and functional programming) as a partially applied function. `(fn this.updateRating song)` takes a function (this.updateRating) and returns another function whose first argument is song. It then passes it along to the StarRating component. When you click the button in that component, it calls that partially applied function with a single parameter, `newRating`. The original `updateRating` function is thus called with two parameters: the first one is `song` (from when we created the `fn` in the template) and the second one is `newRating`. 

I also made an annotated code screenshot (that, if I decide to use something similar, I'll need to update to Octane), which can help people understand how the pieces fit together.

![Image 2019-11-13 at 2 36 49 PM](https://user-images.githubusercontent.com/5022/87060606-03a81f80-c20b-11ea-902f-08a91e375bab.png)

**Comment by lljr** [comment]
I think in Octane `fn` behaves more like an `apply` function. I understood this by comparing them to ELisp.  In https://www.gnu.org/software/emacs/manual/html_node/elisp/Calling-Functions.html, `apply` calls the function with its arguments. So, `(fn @onUpdate star.rating)` calls `@onUpdate` with `star.rating`. In ELisp this would be `(apply 'on-update star-rating)`. I think the `set` helpers looks more like `apply-partially` because the `_` won't be set until the function gets called during component invocation. Like `1+` in ELisp. In ELisp this may look like this `(apply-partially 'set song-rating)`. Although in ELisp using `apply-partially` would not work because it cannot be used with special forms. In ELisp, the function that binds a value to a symbol (variable) is a special form. 

I tried building something similar but it errors out due to what was said just previously: `(defalias 'setlater (apply-partially 'setq 'set-this-to-one))` `(setlater 1)`
