### ISSUE TITLE
[Question] Why not use Route's `transitionTo` method instead of invoking the Router Service?

### ISSUE THREAD

**Issue by lljr** [rockandrollwithemberjs/rarwe-issues#476]
In chapter 10, we're using the Router Service, via `this.router.transitionTo()` inside the the Route's `redirect` hook. I took a look at the API Reference, https://api.emberjs.com/ember/3.20/classes/Route/methods/transitionTo?anchor=transitionTo, and it's possible to use the method defined in the Route class instead of invoking the service. Why not do that? Is there a Ember Classic vs Ember Octane reason for using the Router Service in chapter 10?

Matter of fact, I implemented the transitions in `bands.band.index` with `this.transitionTo` and it works.

**Comment by balinterdi** [comment]
The main reason I'm using `router.transitionTo` everywhere is because I like consistency and, to a lesser extent, because I like using services instead of using the API methods on the objects themselves (that, I think, will probably get deprecated over the long term).

In this case, routes have `this.transitionTo`, while controllers have `this.transitionToRoute`. More consistent is using `this.router.transitionTo` everywhere.

**Comment by lljr** [comment]
@balinterdi Gotcha. I was not aware of the deprecation. I had a feeling this had to do with changes in Ember Octane. 

Thanks!

**Comment by balinterdi** [comment]
I think you meant to make this comment on #477, right?

`route.transitionTo` and `controller.transitionToRoute` are not deprecated, as far as I know.
